language: go
sudo: false

go:
  - 1.6.x
  - 1.9.x
  - 1.10.x

install:
  - go get -t ./...

script:
  - go test -v -covermode=atomic -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)

